version: '3'
services:
  test-gradle-lab:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAMA=${RAMA}
        - TAG=${TAG}
        - TIPO=${TIPO}
    container_name: test-gradle-lab
    env_file:
      - variable.env
