version: '3'
services:
  dockerTC:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REPOSITORIO=${REPOSITORIO}
        - TAG=${TAG}
    container_name: test-gradle
    env_file:
      - variable.env
