version: '3'
services:
  docker-tc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REPOSITORIO=${REPOSITORIO}
        - TAG=${TAG}
        - TIPO=${TIPO}
    container_name: test-gradle
    env_file:
      - variable.env
